blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Follow's Discord Server
    url: https://discord.gg/tUDVZjEr
    about: Want to discuss / chat with the community? Here you go!
  - name: Discuss an issue
    url: https://github.com/hugh-zhan9/Follow/discussions
    about: For general questions, ideas, or non-bug related discussions, please use GitHub Discussions.
